/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  11155111: {
    YourContract: {
      address: "0xc16e7d7a2b1ffb75f15056b36052514ea50bfe78",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_owner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "cancelQuest",
          inputs: [
            {
              name: "_questId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createQuest",
          inputs: [
            {
              name: "_title",
              type: "string",
              internalType: "string",
            },
            {
              name: "_description",
              type: "string",
              internalType: "string",
            },
            {
              name: "_category",
              type: "uint8",
              internalType: "enum YourContract.Category",
            },
            {
              name: "_deadline",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_maxSubmissions",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "emergencyWithdraw",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getOpenQuests",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPhotographerQuests",
          inputs: [
            {
              name: "_photographer",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPhotographerSubmission",
          inputs: [
            {
              name: "_questId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_photographer",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct YourContract.Submission",
              components: [
                {
                  name: "photographer",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "watermarkedPhotoIPFS",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "originalPhotoIPFS",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "submittedAt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "isSelected",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "isPaid",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getQuest",
          inputs: [
            {
              name: "_questId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct YourContract.Quest",
              components: [
                {
                  name: "id",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "requester",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "title",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "description",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "category",
                  type: "uint8",
                  internalType: "enum YourContract.Category",
                },
                {
                  name: "reward",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "deadline",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "status",
                  type: "uint8",
                  internalType: "enum YourContract.QuestStatus",
                },
                {
                  name: "maxSubmissions",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "submissionCount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "selectedCount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "createdAt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "completedAt",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getQuestSubmissions",
          inputs: [
            {
              name: "_questId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple[]",
              internalType: "struct YourContract.Submission[]",
              components: [
                {
                  name: "photographer",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "watermarkedPhotoIPFS",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "originalPhotoIPFS",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "submittedAt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "isSelected",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "isPaid",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getSelectedSubmissions",
          inputs: [
            {
              name: "_questId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple[]",
              internalType: "struct YourContract.Submission[]",
              components: [
                {
                  name: "photographer",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "watermarkedPhotoIPFS",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "originalPhotoIPFS",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "submittedAt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "isSelected",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "isPaid",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getUserQuests",
          inputs: [
            {
              name: "_user",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hasPhotographerSubmitted",
          inputs: [
            {
              name: "_questId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_photographer",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hasSubmitted",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "photographerQuests",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "photographerSubmissionIndex",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "platformFeePercentage",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "questCounter",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "questExists",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "questSubmissions",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "photographer",
              type: "address",
              internalType: "address",
            },
            {
              name: "watermarkedPhotoIPFS",
              type: "string",
              internalType: "string",
            },
            {
              name: "originalPhotoIPFS",
              type: "string",
              internalType: "string",
            },
            {
              name: "submittedAt",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "isSelected",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "isPaid",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "quests",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "requester",
              type: "address",
              internalType: "address",
            },
            {
              name: "title",
              type: "string",
              internalType: "string",
            },
            {
              name: "description",
              type: "string",
              internalType: "string",
            },
            {
              name: "category",
              type: "uint8",
              internalType: "enum YourContract.Category",
            },
            {
              name: "reward",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "deadline",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "status",
              type: "uint8",
              internalType: "enum YourContract.QuestStatus",
            },
            {
              name: "maxSubmissions",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "submissionCount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "selectedCount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "createdAt",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "completedAt",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "selectSubmissions",
          inputs: [
            {
              name: "_questId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_selectedSubmissionIndices",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "submitPhoto",
          inputs: [
            {
              name: "_questId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_watermarkedPhotoIPFS",
              type: "string",
              internalType: "string",
            },
            {
              name: "_originalPhotoIPFS",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "updatePlatformFee",
          inputs: [
            {
              name: "_newFeePercentage",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "userQuests",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "PhotoSubmitted",
          inputs: [
            {
              name: "questId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "photographer",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "watermarkedPhotoIPFS",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "submissionIndex",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PlatformFeeUpdated",
          inputs: [
            {
              name: "oldFee",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "newFee",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "QuestCancelled",
          inputs: [
            {
              name: "questId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "requester",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "refundAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "QuestCompleted",
          inputs: [
            {
              name: "questId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "requester",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "totalSelectedSubmissions",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "totalRewardDistributed",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "platformFee",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "QuestCreated",
          inputs: [
            {
              name: "questId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "requester",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "title",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "category",
              type: "uint8",
              indexed: false,
              internalType: "enum YourContract.Category",
            },
            {
              name: "reward",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "deadline",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "maxSubmissions",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SubmissionsSelected",
          inputs: [
            {
              name: "questId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "requester",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "selectedPhotographers",
              type: "address[]",
              indexed: false,
              internalType: "address[]",
            },
            {
              name: "rewardPerWinner",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 8947400,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
